#!/bin/bash

if which python3 >> /dev/null ; then
	 PYTHON=python3
else
	 PYTHON=python
fi

cd $(dirname "$0")
if echo 'import nose' | $PYTHON ; then
	MODULE="nose -s"
else
	MODULE=unittest
fi

ADD=sprkkr/*/test/test_*.py
for i in "$@" ; do
	if [[ $i != -* ]] ; then
		echo $i
		ADD=
	fi
done

$PYTHON -m $MODULE $@ $ADD
