#!/bin/bash

if which python3 >> /dev/null ; then
	 PYTHON=python3
else
	 PYTHON=python
fi

cd $(dirname "$0")
if echo 'import nose' | $PYTHON ; then
	MODULE="nose -s"
else
	MODULE=unittest
fi

$PYTHON -m $MODULE $@ sprkkr/*/test/test_*.py
