#!/bin/bash

if which python3 >> /dev/null ; then
	 PYTHON=python3
else
	 PYTHON=python
fi

if echo 'import nose' | $PYTHON >> /dev/null ; then
	MODULE="nose -s"
else
	MODULE=unittest
fi


for i in "$@" ; do
	if [[ $i != -* ]] ; then
		ANY=1
	fi
done

ADD=
if [[ ! "$ANY" ]] ; then
	cd $(dirname "$0")
	ADD=sprkkr/*/test/test_*.py
fi
$PYTHON -m $MODULE $@ $ADD
