name: tests
permissions:
  contents: read

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
         mkdir -p ~/.config/matplotlib
         echo "text.usetex : False" >> ~/.config/matplotlib/matplotlibrc
    - run: ./install_dependencies.sh
    - name: Test installed wheel
      run: DO_NOT_RUN_SPRKKR=1 "$GITHUB_WORKSPACE/run_tests"
